### ISSUE TITLE
Font floats up

### ISSUE THREAD

**Issue by DuckDuckWhale** [lapce/lapce#1033]
![imports](https://user-images.githubusercontent.com/28813824/188290812-af926268-f9b5-457f-ae1a-c564a3256d23.png)
![selection](https://user-images.githubusercontent.com/28813824/188290836-c94af2dd-aa26-49fa-8558-4fc9ace0f034.png)
![terminal](https://user-images.githubusercontent.com/28813824/188290830-6dc6f8d2-8417-4d5a-90cf-cb789df5cf62.png)

Ubuntu 22.04, Nvidia, Wayland, a1148e4a1b1f04e50d29456e6b7383f218b73e6c

**Comment by dzhou121** [comment]
Can you please let me the font name?

**Comment by DuckDuckWhale** [comment]
It's DejaVu Sans Mono.

**Comment by panekj** [comment]
This should be fixed, can you test?

**Comment by DuckDuckWhale** [comment]
It's much better now, but it's still not ideal. As compared to VS Code, the font are too low, with the `p`s touching the bottom and leaving more space in the top of the line than desired. Tested with font size of 36 and line height of 50.
![VS Code](https://user-images.githubusercontent.com/28813824/190554608-19ae3a78-4a2e-48fb-acc8-9905f6ff6fa1.png)
![Lapce](https://user-images.githubusercontent.com/28813824/190554606-9f6b6ab2-5d1f-482e-9f6a-566bfd859b4e.png)
![Side by side](https://user-images.githubusercontent.com/28813824/190554934-fb6a74dd-a417-4150-9df6-c8cae8f84130.png)

**Comment by DuckDuckWhale** [comment]
Testing with a line height of 0 on 666c4afac532670d7f22353ceab9c6f599ec6abf results in text going down into the other line:
![overlapping](https://user-images.githubusercontent.com/28813824/190880864-e0554e79-6a4e-42a5-b66b-9fde43baf71f.png)
