### ISSUE TITLE
Mouse hover hint not triggered in macOs 13.0

### ISSUE THREAD

**Issue by Cupnfish** [lapce/lapce#1367]
## Lapce Version

`nightly-d2f2437`

## System information

`13.0 Beta版(22A5352e)`

## Describe the bug

The previous version wouldn't open on macOS 13.0, but since the bug was fixed, I simply used lapce and found that the mouse hover tip feature didn't work.

## Additional information

I haven't checked to see if there are any logs generated currently, I think other users are also experiencing this issue, or I will look at the logs later when I have time

**Comment by MinusGix** [comment]
This should be fixed by #1381.

**Comment by Cupnfish** [comment]
@MinusGix I tested the latest version of nightly today and it didn't fix the problem, I did the same test on my Windows PC and Windows triggers hovering properly but MacOS 13.0 does not, they use the same version of lapce so it seems the issue needs to be reopened.

**Comment by MinusGix** [comment]
Hm, weird but good to know, thanks. The issue fixed it on my system.

**Comment by Cupnfish** [comment]
After doing some debugging, I found that druid itself has this problem and cannot capture mouse move events on macOS 13.0 (it can capture mouse drag, but not mouse move)

**Comment by Cupnfish** [comment]
https://github.com/linebender/druid/issues/2280
