### ISSUE TITLE
odd font rendering of some characters

### ISSUE THREAD

**Issue by extrawurst** [lapce/lapce#1487]
## Lapce Version

0.2.1

## System information

MacOs 12.6 (21G115)

## Describe the bug

weird small rendering of small `i` when using custom font `JetBrains Mono`: 

<img width="202" alt="Screenshot 2022-10-12 at 22 09 57" src="https://user-images.githubusercontent.com/776816/195438531-2ff2da52-1ed1-4318-b3bd-a7c702f11e66.png">

the same looks way better in vscode:

<img width="236" alt="Screenshot 2022-10-12 at 22 12 27" src="https://user-images.githubusercontent.com/776816/195438442-8b632f49-6fb2-4d9a-a360-09674b59210b.png">

**Comment by panekj** [comment]
This is upstream issue in our dependency `swash` https://github.com/dfrg/swash/issues/29

**Comment by panekj** [comment]
This (for some reason) should be fixed now?

**Comment by cpmsmith** [comment]
@panekj I still see this issue in the [latest nightly build](https://github.com/lapce/lapce/commit/6a64a5331ed7f4e4d94f43f21e0336269f70353d):

<img width="140" alt="image" src="https://github.com/lapce/lapce/assets/9437625/b30dd96f-9b79-41ac-b914-a12f43bf54dd">

**Comment by panekj** [comment]
![image](https://github.com/lapce/lapce/assets/50457605/ce57d93f-56b7-4d21-88a2-47e02809fe70)
