### ISSUE TITLE
Input issues

### ISSUE THREAD

**Issue by VarLad** [lapce/lapce#163]
On Fedora 35, GNOME, Wayland. AMD iGPU using Mesa. 

Running Lapce v0.0.11 binary with `WGPU_BACKEND=gl ./lapce`
Issues encountered:
~~1. The cursor doesn't move beyond one line up when I hold the Up key.~~
~~Inteterestingly, when I go into modal mode (Normal), and hold j button, it goes all the way down, but when I hold k button, it doesn't go all the way up.~~
~~2. Can't navigate the text in the terminal using the left and right keys.~~
3. It doesn't seem to scroll down (in disabled modal mode), or up, when I try selecting text with my mouse and drag the mouse down (or up)
~~4. Weird numbering in modal editing, normal and visual modes~~
~~5. `del` key doesn't delete forward~~

**Comment by Abdillah** [comment]
> Weird numbering in modal editing, normal and visual modes

That's numbering is the offset to ease up jumping command, btw.

**Comment by bugadani** [comment]
Thanks for reporting! I believe 1) should be fixed now.

**Comment by bugadani** [comment]
1) should be working on current master
2) should be fixed by #437

**Comment by bugadani** [comment]
3 has been fixed by 99b685a7086a11abb3c37e6f6f062078d02edf4a so I think we can close this collection now :)

**Comment by VarLad** [comment]
@bugadani Just downloaded the latest release. 
Unfortunately, 2. still doesn't work

**Comment by bugadani** [comment]
Please open a new one for that. I didn't notice it among the crossed-out lines 😅
