### ISSUE TITLE
Feature request: implement ctrl+shift+ left or right arrow to select a word at a time

### ISSUE THREAD

**Issue by SingingBush** [lapce/lapce#172]
Being able to <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>left/right</kbd> is really handy

**Comment by SingingBush** [comment]
Yes I think it would be preferable if Lapce used the same key bindings as VSCode by default where possible. There a numerous open issues related to key bindings (It's probably worth adding a _keybinding_ label):

- #25
- #87
- #116
- #170
- #171
- #172
- #173
- #178
- #186
- #202

and a few of them indicate that people are expecting the same bindings as VScode.

**Comment by SingingBush** [comment]
I tried updating my _keymaps-linux.toml_ file to have:

```
[[keymaps]]
key = "ctrl+right"
command = "word_foward"
mode = "nv"

[[keymaps]]
key = "ctrl+left"
command = "word_backward"
mode = "nv"
```

but this did not result in the expected behaviour

**Comment by sgbasaraner** [comment]
+1, I would love to use this for my light text editing as soon as this feature is stable.

**Comment by dzhou121** [comment]
They are fixed in v0.0.12

**Comment by SingingBush** [comment]
I just pulled the latest changes and built from source (on Linux) and was still unable to <kbd>Ctrl</kbd> + <kbd>Left</kbd> or <kbd>Ctrl</kbd> + <kbd>Right</kbd> my way around text.
