### ISSUE TITLE
Increasing UI font size results in settings sidebar text being cropped

### ISSUE THREAD

**Issue by i-ky** [lapce/lapce#2089]
## Lapce Version

0.2.5

## System information

Ubuntu 22.04

## Describe the bug

When UI font size is increased to e.g. 18, the text in the sidebar of settings tab appears cropped.

## Additional information

![image](https://user-images.githubusercontent.com/25753618/215743970-fdcbb04d-9a42-47f0-9f45-62170230b3cb.png)
It looks like the width of the sidebar is not scaled up with UI font size and text wrapping is not enabled as well.

**Comment by felipetesc** [comment]
This also happens if the font family differs:

OS: Windows 11
Arch: x86_x64
Font 

![Untitled](https://user-images.githubusercontent.com/2336812/234086848-24df9d1e-feba-4ad6-8319-84595b8a9f30.jpg)

**Comment by intbyte-100** [comment]
I have a same problem

**Comment by panekj** [comment]
This is fixed in master

**Comment by i-ky** [comment]
I've just tried with v0.3.0 and the issue is still there, the only difference is that now you need a larger font size to trigger it. Previously 18 was enough, now 18 fits fine, but e.g. 22 leads to cropping:
![image](https://github.com/lapce/lapce/assets/25753618/1cb777ab-5e09-41ba-8a4c-09dc93546d1b)
