### ISSUE TITLE
Keyboard shortcuts wrong keyboard layout detection

### ISSUE THREAD

**Issue by RichardFevrier** [lapce/lapce#2731]
## Lapce Version

nightly-b4a6ec5

## System information

Fedora Silverblue 38 Hyprland

## Describe the bug

Using a non QWERTY keyboard resulting in wrong keys detection in the Keyboard Shortcuts section.

E.g. 
Remapping `Ctrl+z` is detected as `Ctrl+w` for undo.

In the rest of the editor everything seems working correctly even pressing `Ctrl+z` really performs undo action (after remapping, read my paragraph below).

Why it is a really problem?
Because by default `Ctrl+z` is mapped to closing the file like a `Ctrl+w` would do... So non QWERTY keyboard users have to remap all non equivalent default shorcuts.

**Comment by zadjadr** [comment]
This might be a hyprland issue, as far as I know: wayland will set the keyboard settings via [xorg](https://wiki.archlinux.org/title/Xorg/Keyboard_configuration).

In my case, hyprland sets the layout correctly (Z is where it physically is), but reports the "us" layout to xorg:

```
❯ setxkbmap -query
WARNING: Running setxkbmap against an Xwayland server
rules:      evdev
model:      pc105
layout:     us
```

I have no workaround, yet.

**Comment by RichardFevrier** [comment]
Read carefully your output `WARNING: Running setxkbmap against an Xwayland server`
XWayland, not wayland.
Nothing related to hyprland, it was working properly in version 0.2.8 this is a regression.

**Comment by Mforcen** [comment]
Keybindings do not work properly also in non-us keyboard layouts. For example I have the es-ES layout and I have to use the keys in the us layout for commands to be launched.

**Comment by joshkamm** [comment]
I'm noticing a similar experience using DVORAK layout on a laptop's QWERTY hardware keyboard on Windows 10, where in version 0.3.0 the Ctrl key bindings are based on their hardware QWERTY positions while in version 0.2.8 they were based on their DVORAK positions.

P.S. Thanks to everyone who volunteers their time to this project. I recently came across it and it looks cool!

**Comment by LuckyTurtleDev** [comment]
> I'm noticing a similar experience using DVORAK layout on a laptop's QWERTY hardware keyboard on Windows 10.

Same with koy on QWERTZ at arch linux.

An overview of some shortcuts:
strg + h save all
strg + ä copy
strg + ü insret
strg + v undo
strg + x redo
strg + a save

This make lapce is unusable for me.

**Comment by saccarosium** [comment]
Same problem on MacOS 14.1.1 with Dvorak

**Comment by iltumio** [comment]
Same for me. Mac OS 14.1.2 with Dvorak layout. Lapce 0.3.1. Physical keyboard is a QWERTY, but the layout configured on the mac is Dvorak US. Looks like the app still see it as QWERTY. The problem started to happen after the recent update that introduced Floem for the UI

**Comment by faern** [comment]
Just wanting to add my +1 to this issue. Discovered and tried out lapce for the first time today. Looks really promising to be honest! Great work devs :sparkles: Sadly it's currently not usable since basically all hotkeys use the wrong keys to be activated.

I'm using it via flatpak on Fedora with sway right now. My keyboard layout is custom (should not matter which one, just not qwerty)

**Comment by owenbrown** [comment]
I use a non-US keyboard layout, so this also makes the product unusable for me.
It prevents me from even testing it.

**Comment by ruabmbua** [comment]
I am running sway, and launching without xwayland (force disabled).
Keyboard layout is QWERTZ, and my system keyboard layout is also set to QWERTZ(german keyboard layout).

The editor functions normally, just keyboard shortcuts do not work correctly.
Sometimes the keyboard shortcuts seem to work for a short while, when I re-focus the editor window.

**Comment by ruabmbua** [comment]
I am hitting the same problem on vscode in wayland mode now.
I have no clue what is going on, but its again only for keyboard shortcuts in the editor.

I think there is something seriously wrong. This all worked in the past, I am not sure any more if its an issue with lapce / vscode or with some other component...

**Comment by saccarosium** [comment]
Hey @ruabmbua, I've tried vscode on gnome, under wayland, an I didn't have encounter this problem. Try to see if it is a problem with [wlroots](https://gitlab.freedesktop.org/wlroots/wlroots) witch is the library that sway is based on.

**Comment by melMass** [comment]
Same on windows with an AZERTY layout

**Comment by LuckyTurtleDev** [comment]
Anything new at this issue? It is a big deal breaker which make lape useless for all non us people/keyboards.

**Comment by ruabmbua** [comment]
I have reproduced the issue at least one time in gnome now.

**Comment by panekj** [comment]
> Anything new at this issue? It is a big deal breaker which make lape useless for all non us people/keyboards.

If there will be, it will be mentioend in this issue

**Comment by panekj** [comment]
There is already PR opened (#2637) to fix the problem and issue for discussion (#2636)

**Comment by dzhou121** [comment]
This is potentially fixed by https://github.com/lapce/lapce/pull/3119

**Comment by dzhou121** [comment]
@RichardFevrier Would love to hear your feedback if the PR fixes the issue for you. It should be available on the latest nightly build.

**Comment by RichardFevrier** [comment]
Thanks for asking @dzhou121

Just tested and it's working well for some shortcuts not so much for some others (I have deleted the entire `.config/lapce-nightly` first).

E.g.
`Ctrl + z` working well out of the box now!
`Ctrl + /` (toggle comment) not working, and if i check to remap it, it was recognized as `Ctrl + Shift + :`

Maybe something on my side, I've tested 2 differents linux desktop environment (`Gnome` and `Niri` both under `Wayland`) so if some people using linux from this conversation would mind to test also that would be nice.

Thanks for reading me.

**Comment by saccarosium** [comment]
I'm happy to report that the keybindings works with no problem here on Debian 12 Gnome Wayland with dvorak.

**Comment by LuckyTurtleDev** [comment]
Can confirm that the shortcuts seems to work again (german key board + koy layout) on commit 21e6719.

But it looks like `strg` + `+` does still not work for zooming. But `strg` + `-` works. (I am not sure if I had accidentally disable it, but I was not able to find the keyboard shortcut section in the settings.

**Comment by dzhou121** [comment]
> Can confirm that the shortcuts seems to work again (german key board + koy layout) on commit [21e6719](https://github.com/lapce/lapce/commit/21e6719af2153ebf5304c6dbcbb63a147a1ae16a).
> 
> But it looks like `strg` + `+` does still not work for zooming. But `strg` + `-` works. (I am not sure if I had accidentally disable it, but I was not able to find the keyboard shortcut section in the settings.
> 
> Update: found shortcut settings. Zoom was set to `strg` + `=`. But after changing it does still not work. In the shortcut overview it does show `strg+` instead of `strg++`. ![image](https://private-user-images.githubusercontent.com/44570204/318038708-703e05c4-b4cf-45ad-86d0-2f737d7c3f3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTM4MzksIm5iZiI6MTcxMTcxMzUzOSwicGF0aCI6Ii80NDU3MDIwNC8zMTgwMzg3MDgtNzAzZTA1YzQtYjRjZi00NWFkLTg2ZDAtMmY3MzdkN2MzZjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDExNTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZTNiOWJhMzE1NjRmOTY1NDZjMTc1MTUwNzk4NDAzN2FjYjMzMGEzNjZkMTVjZjA5M2FhNTUyZTUwYzAxZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3ro1NMNxq8WSqeL-rQD0fqaiERwS67-FG3mC0-xXiKk)

Thanks for testing it. Can you please see what was the raw keyboard event in Lapce logs when you press Ctrl++

**Comment by LuckyTurtleDev** [comment]
> > Can confirm that the shortcuts seems to work again (german key board + koy layout) on commit [21e6719](https://github.com/lapce/lapce/commit/21e6719af2153ebf5304c6dbcbb63a147a1ae16a).
> > But it looks like `strg` + `+` does still not work for zooming. But `strg` + `-` works. (I am not sure if I had accidentally disable it, but I was not able to find the keyboard shortcut section in the settings.
> > Update: found shortcut settings. Zoom was set to `strg` + `=`. But after changing it does still not work. In the shortcut overview it does show `strg+` instead of `strg++`. ![image](https://private-user-images.githubusercontent.com/44570204/318038708-703e05c4-b4cf-45ad-86d0-2f737d7c3f3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTM4MzksIm5iZiI6MTcxMTcxMzUzOSwicGF0aCI6Ii80NDU3MDIwNC8zMTgwMzg3MDgtNzAzZTA1YzQtYjRjZi00NWFkLTg2ZDAtMmY3MzdkN2MzZjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDExNTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZTNiOWJhMzE1NjRmOTY1NDZjMTc1MTUwNzk4NDAzN2FjYjMzMGEzNjZkMTVjZjA5M2FhNTUyZTUwYzAxZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3ro1NMNxq8WSqeL-rQD0fqaiERwS67-FG3mC0-xXiKk)
> 
> Thanks for testing it. Can you please see what was the raw keyboard event in Lapce logs when you press Ctrl++

Dump question, but how do I get logs. I have try `RUST_LOG=debug lapce -w` but it does not output anything.


One additional information: the shortcut preview show correctly `strg++` but after pressing save it shows only `strg+`
![image](https://github.com/lapce/lapce/assets/44570204/f4f273cf-1ec5-42e7-89ae-f13b3da2c42c)

**Comment by dzhou121** [comment]
> > > Can confirm that the shortcuts seems to work again (german key board + koy layout) on commit [21e6719](https://github.com/lapce/lapce/commit/21e6719af2153ebf5304c6dbcbb63a147a1ae16a).
> > > But it looks like `strg` + `+` does still not work for zooming. But `strg` + `-` works. (I am not sure if I had accidentally disable it, but I was not able to find the keyboard shortcut section in the settings.
> > > Update: found shortcut settings. Zoom was set to `strg` + `=`. But after changing it does still not work. In the shortcut overview it does show `strg+` instead of `strg++`. ![image](https://private-user-images.githubusercontent.com/44570204/318038708-703e05c4-b4cf-45ad-86d0-2f737d7c3f3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTM4MzksIm5iZiI6MTcxMTcxMzUzOSwicGF0aCI6Ii80NDU3MDIwNC8zMTgwMzg3MDgtNzAzZTA1YzQtYjRjZi00NWFkLTg2ZDAtMmY3MzdkN2MzZjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDExNTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZTNiOWJhMzE1NjRmOTY1NDZjMTc1MTUwNzk4NDAzN2FjYjMzMGEzNjZkMTVjZjA5M2FhNTUyZTUwYzAxZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3ro1NMNxq8WSqeL-rQD0fqaiERwS67-FG3mC0-xXiKk)
> > 
> > 
> > Thanks for testing it. Can you please see what was the raw keyboard event in Lapce logs when you press Ctrl++
> 
> Dump question, but how do I get logs? I have try `RUST_LOG=debug lapce -w` but it does not output anything.
> 
> One additional information: the shortcut preview show correctly `ctrl++` but after pressing save it shows only `ctrl+` ![image](https://private-user-images.githubusercontent.com/44570204/318066470-f4f273cf-1ec5-42e7-89ae-f13b3da2c42c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MjIzMDgsIm5iZiI6MTcxMTcyMjAwOCwicGF0aCI6Ii80NDU3MDIwNC8zMTgwNjY0NzAtZjRmMjczY2YtMWVjNS00MmU3LTg5YWUtZjEzYjNkYTJjNDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDE0MjAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMzEyMjllYWYzZTNlMDVlNWQwZDUzNGE3ZWRiZDFiODI3ZDNlMzgyMDY4Yjg5MGQzMjQ2MGEyMmU5ODNkNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qzQdwtBGvDP86tUdk7lIdEYJn5FHMvcGsVWos00pHzA)

You can search "open log" in command palette.  But I see it's a bug now, when we try to parse the keymap, we simply `string.split('+')` and it gets rid of the last `+`.

**Comment by dzhou121** [comment]
> > > Can confirm that the shortcuts seems to work again (german key board + koy layout) on commit [21e6719](https://github.com/lapce/lapce/commit/21e6719af2153ebf5304c6dbcbb63a147a1ae16a).
> > > But it looks like `strg` + `+` does still not work for zooming. But `strg` + `-` works. (I am not sure if I had accidentally disable it, but I was not able to find the keyboard shortcut section in the settings.
> > > Update: found shortcut settings. Zoom was set to `strg` + `=`. But after changing it does still not work. In the shortcut overview it does show `strg+` instead of `strg++`. ![image](https://private-user-images.githubusercontent.com/44570204/318038708-703e05c4-b4cf-45ad-86d0-2f737d7c3f3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTM4MzksIm5iZiI6MTcxMTcxMzUzOSwicGF0aCI6Ii80NDU3MDIwNC8zMTgwMzg3MDgtNzAzZTA1YzQtYjRjZi00NWFkLTg2ZDAtMmY3MzdkN2MzZjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDExNTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZTNiOWJhMzE1NjRmOTY1NDZjMTc1MTUwNzk4NDAzN2FjYjMzMGEzNjZkMTVjZjA5M2FhNTUyZTUwYzAxZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3ro1NMNxq8WSqeL-rQD0fqaiERwS67-FG3mC0-xXiKk)
> > 
> > 
> > Thanks for testing it. Can you please see what was the raw keyboard event in Lapce logs when you press Ctrl++
> 
> Dump question, but how do I get logs? I have try `RUST_LOG=debug lapce -w` but it does not output anything.
> 
> One additional information: the shortcut preview show correctly `ctrl++` but after pressing save it shows only `ctrl+` ![image](https://private-user-images.githubusercontent.com/44570204/318066470-f4f273cf-1ec5-42e7-89ae-f13b3da2c42c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MjIzMDgsIm5iZiI6MTcxMTcyMjAwOCwicGF0aCI6Ii80NDU3MDIwNC8zMTgwNjY0NzAtZjRmMjczY2YtMWVjNS00MmU3LTg5YWUtZjEzYjNkYTJjNDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDE0MjAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMzEyMjllYWYzZTNlMDVlNWQwZDUzNGE3ZWRiZDFiODI3ZDNlMzgyMDY4Yjg5MGQzMjQ2MGEyMmU5ODNkNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qzQdwtBGvDP86tUdk7lIdEYJn5FHMvcGsVWos00pHzA)

should be fixed by 0f9090640bcc72b2c230e6f122350abffaca4ec2

**Comment by LuckyTurtleDev** [comment]
It works now for numeric keypad again. But for the other `+` at keyboard layer 3 does still not work.
If I try to use the other `+` as shortcut with `ctrl` I get this:
![image](https://github.com/lapce/lapce/assets/44570204/a7b5a987-3f25-498f-bd86-494c4f98712b)
Maybe lapce get confused by the unusual layout.
koy layer3:
![image](https://www.maximilian-schillinger.de/img/Neo_Ebene3.png)

log:
```
2024-03-29T20:11:42.650499Z DEBUG lapce_app::keypress: Keyboard(KeyEvent { key: KeyEvent { physical_key: Code(ControlLeft), logical_key: Named(Control), text: None, location: Left, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Named(Control), text_with_all_modifiers: None } }, modifiers: ModifiersState(0x0) })
2024-03-29T20:11:43.449949Z DEBUG lapce_app::keypress: Keyboard(KeyEvent { key: KeyEvent { physical_key: Code(CapsLock), logical_key: Named(AltGraph), text: None, location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Named(AltGraph), text_with_all_modifiers: None } }, modifiers: ModifiersState(CONTROL) })
2024-03-29T20:11:44.433948Z DEBUG lapce_app::keypress: Keyboard(KeyEvent { key: KeyEvent { physical_key: Code(KeyM), logical_key: Character("%"), text: Some("%"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("p"), text_with_all_modifiers: Some("%") } }, modifiers: ModifiersState(CONTROL) })
```

**Comment by dzhou121** [comment]
> It works now for numeric keypad again. But for the other `+` at keyboard layer 3 does still not work. If I try to use the other `+` as shortcut with `ctrl` I get this: ![image](https://private-user-images.githubusercontent.com/44570204/318128955-a7b5a987-3f25-498f-bd86-494c4f98712b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NDQ4NzgsIm5iZiI6MTcxMTc0NDU3OCwicGF0aCI6Ii80NDU3MDIwNC8zMTgxMjg5NTUtYTdiNWE5ODctM2YyNS00OThmLWJkODYtNDk0YzRmOTg3MTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDIwMzYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZWJmMGNkYTRhNjJmYjYxYTFjOGM3M2JhZjU5OTAwNTkyMjc4MDI3MDUxYTVkNWFiOGY5NWQ5NmU2NmIyOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.82Ev0WzjJZCVDDw6qZn-zQosiIY_jAQ3k0TWJrFIbis) Maybe lapce get confused by the unusual layout. koy layer3: ![image](https://camo.githubusercontent.com/7a51a12bb6a2b887b57759aa367bbcbc798011e0e87ffd98b80dbda983b453d2/68747470733a2f2f7777772e6d6178696d696c69616e2d736368696c6c696e6765722e64652f696d672f4e656f5f4562656e65332e706e67)
> 
> log:
> 
> ```
> 2024-03-29T20:11:42.650499Z DEBUG lapce_app::keypress: Keyboard(KeyEvent { key: KeyEvent { physical_key: Code(ControlLeft), logical_key: Named(Control), text: None, location: Left, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Named(Control), text_with_all_modifiers: None } }, modifiers: ModifiersState(0x0) })
> 2024-03-29T20:11:43.449949Z DEBUG lapce_app::keypress: Keyboard(KeyEvent { key: KeyEvent { physical_key: Code(CapsLock), logical_key: Named(AltGraph), text: None, location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Named(AltGraph), text_with_all_modifiers: None } }, modifiers: ModifiersState(CONTROL) })
> 2024-03-29T20:11:44.433948Z DEBUG lapce_app::keypress: Keyboard(KeyEvent { key: KeyEvent { physical_key: Code(KeyM), logical_key: Character("%"), text: Some("%"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("p"), text_with_all_modifiers: Some("%") } }, modifiers: ModifiersState(CONTROL) })
> ```

Was it AltGraph that changed it to layer 3?

**Comment by NicoAdrian** [comment]
Same problem with MacOS Sonoma (french keyboard - AZERTY). Good editor and looks promising but unusable when trying to add/change new keybindings

**Comment by RichardFevrier** [comment]
Just to add some infos about my previous comment:

> `Ctrl + /` (toggle comment) not working, and if i check to remap it, it was recognized as `Ctrl + Shift +` :

I have checked my inputs with `wev` from the lapce console. And I can confirm that `/` is outputed.
Here it is if it can help:
```
[14:     wl_keyboard] key: serial: 21542; time: 3610605; key: 62; state: 1 (pressed)
                      sym: Shift_R      (65506), utf8: ''
[14:     wl_keyboard] modifiers: serial: 21542; group: 0
                      depressed: 00000001: Shift
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] key: serial: 21543; time: 3610860; key: 60; state: 1 (pressed)
                      sym: slash        (47), utf8: '/'
```

**Comment by dzhou121** [comment]
> Just to add some infos about my previous comment:
> 
> > `Ctrl + /` (toggle comment) not working, and if i check to remap it, it was recognized as `Ctrl + Shift +` :
> 
> I have checked my inputs with `wev` from the lapce console. And I can confirm that `/` is outputed. Here it is if it can help:
> 
> ```
> [14:     wl_keyboard] key: serial: 21542; time: 3610605; key: 62; state: 1 (pressed)
>                       sym: Shift_R      (65506), utf8: ''
> [14:     wl_keyboard] modifiers: serial: 21542; group: 0
>                       depressed: 00000001: Shift
>                       latched: 00000000
>                       locked: 00000000
> [14:     wl_keyboard] key: serial: 21543; time: 3610860; key: 60; state: 1 (pressed)
>                       sym: slash        (47), utf8: '/'
> ```

I get what you mean. But it’s the logic of Lapce that if shift is pressed, then we’ll use shift+key_before_modifier as the input.

**Comment by RichardFevrier** [comment]
I see now; thanks for the explanation!
And since US/UK Qwerty `/` does not need `Shift` to be applied you did not encountered the problem.
But it still exists for the rest of the world, at least for european countries =)

**Comment by dzhou121** [comment]
> I see now; thanks for the explanation! And since US/UK Qwerty `/` does not need `Shift` to be applied you did not encountered the problem. But it still exists for the rest of the world, at least for european countries =)

Yeah `shift` is a tricky one. We did this way because it's easier for capital letters. E.g. it's more obvious for `shift+p` than `P` in the key bindings.

**Comment by LuckyTurtleDev** [comment]
> > At the quertz layout at this position is caps lock. At the grafic it is called M3.
> 
> should be fixed by #3143, can you please test it?

sorry I was not able to test it until now. Because I did not have access to my tower last week and my laptop was not able to compile lapce, because it needs too much ram.

I have test it again with the lasted commit and get this now:
![image](https://github.com/lapce/lapce/assets/44570204/dd4640d6-ec93-4138-a9d4-c2d7cfbcb275)

So it does still not detect it as `Ctrl` and `+`. Instead it use the modifier and  `p`  which is the key on this position without pressing the `M3` modifier. 
One thing I notify is that lapce did show `Ctrl+AltGraph` first and if i press +/p it changes to  `Ctrl+AltGr+p`.
However the generated `Ctrl+AltGr+p` works for zooming.

Lapce hat also stop generating log for setting keyboard shortcuts. So I can not provide any.

**Comment by RichardFevrier** [comment]
Just so you know there are nightly builds @LuckyTurtleDev

**Comment by dzhou121** [comment]
> > > At the quertz layout at this position is caps lock. At the grafic it is called M3.
> > 
> > 
> > should be fixed by #3143, can you please test it?
> 
> sorry I was not able to test it until now. Because I did not have access to my tower last week and my laptop was not able to compile lapce, because it needs too much ram.
> 
> I have test it again with the lasted commit and get this now: ![image](https://private-user-images.githubusercontent.com/44570204/320280625-dd4640d6-ec93-4138-a9d4-c2d7cfbcb275.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MjE1ODQsIm5iZiI6MTcxMjUyMTI4NCwicGF0aCI6Ii80NDU3MDIwNC8zMjAyODA2MjUtZGQ0NjQwZDYtZWM5My00MTM4LWE5ZDQtYzJkN2NmYmNiMjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDIwMjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYTk1ZWUzMGNmNjZhZTUwOTNlZjY5NGVkNTBlODIyOTc5ODVjYzRiOTA1MDFjODI0YmIyN2EwMWQ2YTU4ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zOT--h2AfmIbeUzJD8O-zD6Fd6dv71OQagUuqOi-364)
> 
> So it does still not detect it as `Ctrl` and `+`. Instead it use the modifier and `p` which is the key on this position without pressing the `M3` modifier. One thing I notify is that lapce did show `Ctrl+AltGraph` first and if i press +/p it changes to `Ctrl+AltGr+p`. However the generated `Ctrl+AltGr+p` works for zooming.
> 
> Lapce hat also stop generating log for setting keyboard shortcuts. So I can not provide any.

From the log you showed earlier, `AltGr` was sent to Lapce by winit when you press M3, so what I did is to recognise `AltGr` as a modifier, and then use the key_without_modifier which is `p` in this case. So it showed as `ctrl`+`AltGr` + `p`.

Take US layout for example, `!` would be shown as `shift+1` in keybindings.

**Comment by LuckyTurtleDev** [comment]
I found another issue. The arrow keys at layer 4 do also not work. At lapce 0.2.0 I was able to move the cursor with them. I was not able to reproduce this issue with any other software.

![koy](https://www.maximilian-schillinger.de/img/KOY_Ebene4.png)

**Comment by dzhou121** [comment]
> I found another issue. The arrow keys at layer 4 do also not work. At lapce 0.2.0 I was able to move the cursor with them. I was not able to reproduce this issue with any other software.
> 
> ![koy](https://camo.githubusercontent.com/59a96f4910a3df0e579b71a7982c462330896f944f8fbac0160ff0b2194c4c3c/68747470733a2f2f7777772e6d6178696d696c69616e2d736368696c6c696e6765722e64652f696d672f4b4f595f4562656e65342e706e67)

It's probably because of modifier key again, so it will recognise it as something + the base key
