### ISSUE TITLE
Operation timed out when publishing a theme

### ISSUE THREAD

**Issue by nullndr** [lapce/lapce#3569]
Hey I'm not this is the correct place to open this kind of issue, feel free to move this where is more appropriate.

Basically I'm trying to publish a new version of the [material icon theme](https://github.com/nullndr/lapce-material-icon-theme/) but volts raise an unhandled error:

```
thread 'main' panicked at /home/andrea/.cargo/registry/src/index.crates.io-6f17d22bba15001f/volts-0.2.1/src/commands.rs:131:10:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("plugins.lapce.dev")), port: None, path: "/api/v1/plugins/new", query: None, fragment: None }, source: TimedOut }
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: volts::commands::publish
   4: volts::cli
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

So I rebuilt `volts-cli` locally with this little edit:

```rust
    let resp = reqwest::blocking::Client::new()
        .request(Method::PUT, "https://plugins.lapce.dev/api/v1/plugins/new")
        .bearer_auth(token.trim())
        .body(File::open(&archive_path).unwrap())
        .send();

    match resp {
        Ok(resp) => {
            if resp.status() == StatusCode::OK {
                println!("plugin published successfully");
                return;
            }

            eprintln!("{}", resp.text().unwrap());
        }

        Err(error) => {
            println!("{}", error);
            return;
        }
    }
```

That prints the following error:

```
error sending request for url (https://plugins.lapce.dev/api/v1/plugins/new): operation timed out
```

**Comment by panekj** [comment]
Issue should be resolved now, I deployed updated configuration for the connection limit, ref: https://github.com/lapce/lapce-volts/pull/12

**Comment by nullndr** [comment]
@panekj hey, I just tested again but the error is still raised 😭

**Comment by nullndr** [comment]
@panekj sorry to bother you but do you have any news? Im still facing the same issue
