### ISSUE TITLE
Changing font has no effect, settings aren't saved

### ISSUE THREAD

**Issue by DanielJoyce** [lapce/lapce#73]
Change font, exit settings screen, exit lapce, restart, font settings aren't changed.

**Comment by DanielJoyce** [comment]
Ahh, I go to command menu, "Open settings file", and then if I use the settings window, it works.

Otherwise it doesn't seem to create it

**Comment by dzhou121** [comment]
Should be fixed by the latest release v0.0.10

**Comment by bugadani** [comment]
Thanks for reportin this issue! As this is supposed to be fixed, I'm closing this. However, feel free to reopen if you still experience the problem!

**Comment by FlooferLand** [comment]
https://github.com/user-attachments/assets/2271cead-0110-4249-b708-f8205107485c

Issue still occurs! I'm not sure why.
I've had this same issue about a year ago when I first tried Lapce as well.
Fresh install, installed with WinGet on a fresh install of Windows 11.
