### ISSUE TITLE
file explorer side bar not updating

### ISSUE THREAD

**Issue by DaQueenJodi** [lapce/lapce#730]
When I rename files or create new ones, they do get created/renamed but the change isn't reflected on the file explorer tab, even if it's done within lapce

I am using the latest nightly build on Linux

**Comment by codingJJJ** [comment]
me too

**Comment by MinusGix** [comment]
For within Lapce, this should be fixed by https://github.com/lapce/lapce/commit/1008682d285635fdc5ebb36c65eb99919740f9e4

**Comment by awulkan** [comment]
> For within Lapce, this should be fixed by [1008682](https://github.com/lapce/lapce/commit/1008682d285635fdc5ebb36c65eb99919740f9e4)

It's still a problem for me. These are all the same file that I just renamed.
![File names](https://i.imgur.com/Vf4GrWZ.png)

**Comment by dzhou121** [comment]
@awulkan 

Does it appear if you right click and "refresh"?

**Comment by awulkan** [comment]
@dzhou121 Refreshing doesn't help. They're still there.
I'm on a Mac Mini M1, if that makes any difference.

**Comment by dzhou121** [comment]
> @dzhou121 Refreshing doesn't help. They're still there. I'm on a Mac Mini M1, if that makes any difference.

Ah you mean the old files are still in the editor tabs. It's a different issue.

**Comment by awulkan** [comment]
Yes exactly, and in the "Open Editors" section. 
Should a new issue be created for this?

**Comment by dzhou121** [comment]
> Yes exactly. Should a new issue be created for this?

Yes please

**Comment by panekj** [comment]
Closing since this is fixed
